### ISSUE TITLE
One Link is not visible in dark theme

### ISSUE THREAD

**Issue by prabirshrestha** [onejs/one#254] opened 2024-11-24 21:42 UTC
Repro steps:
* Create an empty One app
* Add `<Link href="/">Go to homepage</Link>` component to one of the page.
* Open the app in the browser or iOS in dark theme you will see the text missing due to being the same color as the background.

Light theme works:

![image](https://github.com/user-attachments/assets/d7b10b1f-fdbc-48df-8b69-ad01b7c369f4)

Dark theme has bug: (notice Go to homepage is not visible).
![image](https://github.com/user-attachments/assets/a24c4138-9813-4b88-bca6-8f515e022350)

**Comment by prabirshrestha** [comment] 2024-11-24 21:58
Seems like a temporary work around is to add Text from tamagui.

```typescript
<Link to="/">
  <Text>Go to homepage</Text>
</Link>
```

Would be good to register it globally so if one of the engineer is using light theme they might forget to wrap it in Text and it will have bugs in dark theme. This way just `<Link to="/>Go to homepage</Link>` works.

**Comment by natew** [comment] 2024-12-01 22:26
Yea the Link just uses plain Text behind the scenes, which doesn't have any special light/dark support. You'd need a library like Tamagui to support that. Closing for now since it's not a bug, just something to know.

**Closed by natew** 2024-12-01 22:26 UTC
